# Generated by Django 2.2.2 on 2019-07-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('numeroMovil', models.IntegerField(primary_key=True, serialize=False)),
                ('clase', models.CharField(choices=[('A', 'Avanzada'), ('B', 'Basica')], default='B', max_length=1)),
                ('marca', models.CharField(max_length=35)),
                ('modeloA', models.CharField(max_length=35)),
                ('placa', models.CharField(max_length=35)),
                ('servicio', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], default='L', max_length=1)),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='')),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=35)),
                ('telefono', models.IntegerField()),
                ('nivel', models.CharField(choices=[('1', 'Nivel I'), ('2', 'Nivel II'), ('3', 'Nivel III')], default='1', max_length=10)),
                ('especialidad', models.CharField(choices=[('T', 'Traumatología'), ('U', 'Urología'), ('O', 'Otorrinolaringología'), ('OF', 'Oftalmología'), ('GOT', 'Ginecología y obstetricia o tocología'), ('DQV', 'Dermatología médico-quirúrgica y venereología')], default='T', max_length=35)),
                ('numeroCamas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('apP', models.CharField(max_length=255)),
                ('apnP', models.CharField(max_length=255)),
                ('emailP', models.EmailField(max_length=254)),
                ('telefonoP', models.IntegerField()),
            ],
        ),
    ]
