# Generated by Django 2.2.2 on 2019-07-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('audio', models.FileField(upload_to='sound/')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsamuems.NivelHospital'),
        ),
    ]
