# Generated by Django 2.2.4 on 2019-08-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergenciaSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonostico', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('sintomas', models.CharField(blank=True, max_length=255)),
                ('equipos', models.CharField(blank=True, max_length=255)),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
                ('estadoEmergencia', models.CharField(blank=True, choices=[('T', 'Terminada'), ('E', 'En curso'), ('C', 'Cancelada'), ('L', 'Libre')], default='E', max_length=1)),
                ('comentarios', models.CharField(blank=True, max_length=255)),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appsamuems.Ambulancia')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appsamuems.Hospital')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appsamuems.Paciente')),
            ],
        ),
    ]
