# Generated by Django 2.2.2 on 2019-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.IntegerField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
