# Generated by Django 2.2.2 on 2019-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0002_auto_20190616_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('numeroMovil', models.IntegerField(primary_key=True, serialize=False)),
                ('clase', models.CharField(choices=[('A', 'Avanzada'), ('B', 'Basica')], default='B', max_length=1)),
                ('marca', models.CharField(max_length=35)),
                ('modelo', models.CharField(max_length=35)),
                ('placa', models.CharField(max_length=35)),
                ('servicio', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], default='L', max_length=1)),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='')),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
