# Generated by Django 2.2.4 on 2019-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0002_emergenciasnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergenciasnippet',
            name='fechaReporte',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
