# Generated by Django 2.2.2 on 2019-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0003_auto_20190718_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
    ]
