# Generated by Django 2.2.4 on 2019-08-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0003_auto_20190815_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivosnippet',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='emergenciasnippet',
            name='fechaReporte',
        ),
    ]
