# Generated by Django 2.2.4 on 2019-08-17 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0004_auto_20190817_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosnippet',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='emergenciasnippet',
            name='fechaReporte',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
