# Generated by Django 2.2.2 on 2019-07-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0004_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulancia',
            old_name='modelo',
            new_name='modeloA',
        ),
    ]
