# Generated by Django 2.2.4 on 2019-08-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0005_auto_20190817_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosnippet',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='archivosnippet',
            name='lon',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
