# Generated by Django 2.2.2 on 2019-07-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsamuems', '0005_auto_20190704_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancia',
            name='foto',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
